enum ACTIONS {
    MAKE_REQUEST = 'MAKE_REQUEST',
    SET_CURRENT_BOOK = 'SET_CURRENT_BOOK',
    END_REQUEST = 'END_REQUEST',
    SET_ERROR = 'SET_ERROR',
    CLEAR_ERROR = 'CLEAR_ERROR'
}

export { ACTIONS }